### PR TITLE
Upgrade from Docker Engine version 1.12.1 to 1.12.3

### PR DESCRIPTION
**Pull request by alex-berger**
Upgrade to the newest minor release of Docker Engine 1.12.

### CODE REVIEW

**Comment by joshwget** [comment]
Thanks @alex-berger! Just a few comments on this.
- Can you move the `.gitignore` to a separate commit?
- Can you keep Docker 1.12.1 as it is? (add new files rather than change the existing ones)
- Can you remove `dist/images`?

**Comment by alex-berger** [comment]
OK, done.

**Comment by joshwget** [comment]
LGTM!

@SvenDowideit

**Comment by joshwget** [comment]
@alex-berger The other half of this is adding the corresponding service to the [rancher/os-services repo](https://github.com/rancher/os-services). If you're interesting in adding it there as well, I'd wait for rancher/os-services#53.

**Comment by alex-berger** [comment]
Done, https://github.com/rancher/os-services/pull/52. Do I also have to make a PR for rancher/os?

**Comment by SvenDowideit** [comment]
LGTM!

**Comment by SvenDowideit** [comment]
@alex-berger can you update this PR to 1.12.3 please?

**Comment by SvenDowideit** [comment]
https://forums.docker.com/t/docker-1-12-2-security-advisory/23975

**Comment by SvenDowideit** [comment]
LGTM

**Pull request merged**
